import { noticeTypeLabel, SERVICE_METHOD_LABELS } from '@rental/core/notices'
import { friendlyDate } from '@rental/core/scheduling'
import Link from 'next/link'
import { requireScope } from '@/lib/auth/guard.ts'
import { listNotices } from '@/lib/notices/queries.ts'
import { currentScope } from '@/lib/scope/current-scope.ts'

export const metadata = { title: 'Notices — Rental Operations' }

// The notice register (COMM-02, R-051).
//
// UNSERVED FIRST, because a notice that has been drafted and not served is
// work somebody still has to do, and one that has been served is a record.
// The whole point of the screen is that the first kind cannot be forgotten.
//
// `requireScope`, not a bare `requirePermission('notice.read')` - the same
// dormant scoping bug R-008 found and R-050 found again: a resource-less
// check asks "may you see every notice everywhere", which no property-scoped
// manager can answer yes to.

export default async function NoticesPage() {
  const { actor } = await requireScope('notice.read')
  const scope = await currentScope(actor)
  const notices = await listNotices(scope)

  const unserved = notices.filter((notice) => !notice.servedAt)

  return (
    <div className="flex max-w-4xl flex-col gap-6">
      <header className="flex flex-col gap-1">
        <h1 className="text-2xl font-semibold tracking-tight">Notices</h1>
        <p className="text-muted-foreground text-sm">
          {notices.length} notice{notices.length === 1 ? '' : 's'} across{' '}
          {scope.propertyIds.length} propert{scope.propertyIds.length === 1 ? 'y' : 'ies'}
          {unserved.length > 0 && ` · ${unserved.length} not yet served`}.
        </p>
      </header>

      {notices.length === 0 ? (
        <p className="text-muted-foreground text-sm">
          No notices yet. They are generated by the flows that need them — an entry
          notice when a work order is scheduled, a repair charge when a tenant is
          billed for damage.
        </p>
      ) : (
        <ul className="flex flex-col divide-y rounded-md border">
          {notices.map((notice) => {
            // EITHER a lease or an applicant (R-061's either/or) - whichever
            // this notice actually has names the recipient.
            const tenant = notice.lease?.leaseTenants[0]?.tenant
            const recipientName = tenant
              ? `${tenant.firstName} ${tenant.lastName}`
              : notice.applicant
                ? `${notice.applicant.firstName} ${notice.applicant.lastName} (applicant)`
                : 'No recipient on file'
            const methods = notice.deliveries.map((d) => SERVICE_METHOD_LABELS[d.method] ?? d.method)
            return (
              <li key={notice.id}>
                <Link
                  href={`/notices/${notice.id}`}
                  className="hover:bg-accent focus-visible:ring-ring flex min-h-14 flex-col gap-1 px-4 py-3 focus-visible:ring-2 focus-visible:-outline-offset-2 focus-visible:outline-none"
                >
                  <span className="flex flex-wrap items-center justify-between gap-2">
                    <span className="font-medium">
                      {noticeTypeLabel(notice.type)} — {notice.property.name}
                      {notice.lease?.unit ? ` · ${notice.lease.unit.name}` : ''}
                    </span>
                    {notice.servedAt ? (
                      <span className="rounded-full bg-green-100 px-2 py-0.5 text-xs font-medium text-green-900">
                        Served {friendlyDate(notice.servedAt, notice.property.timezone)}
                      </span>
                    ) : (
                      <span className="rounded-full bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-900">
                        Not served
                      </span>
                    )}
                  </span>
                  <span className="text-muted-foreground text-sm">
                    {recipientName}
                    {' · '}
                    {methods.length > 0 ? methods.join(' + ') : 'no service recorded'}
                    {notice.documentId && ' · PDF archived'}
                  </span>
                </Link>
              </li>
            )
          })}
        </ul>
      )}
    </div>
  )
}
