import { clampToStateCap, formatCents, prorateRent } from '@rental/core/money'

// STATICALLY PRERENDERED UNTIL D-138, AND THAT SILENTLY BROKE EVERY SCRIPT
// ON IT. The CSP carries a per-request nonce, and prerendered HTML is fixed
// at build time - so there is no request for a nonce to come from, and Next
// stamps none. `'strict-dynamic'` then makes `'self'` inert, so all fourteen
// script tags on this page were refused by the browser. Nothing went red:
// this product uses real `<form action>` rather than `onClick`, so the page
// still worked server-side, which is exactly how it stayed invisible.
//
// Rendering per request is what lets the nonce exist. The cost is one
// uncached render of a page nobody hits in a loop; the alternative is a
// policy this page cannot satisfy.
export const dynamic = 'force-dynamic'


// Placeholder home route. R-007 replaces this with the admin shell; R-013
// replaces that with the real owner dashboard. It exists now so the scaffold
// has something to lint, build, axe-scan and measure - and so the money
// helpers are exercised by something other than their own unit tests.
export default function Home() {
  const example = prorateRent({
    monthlyRentCents: 185_000,
    daysOccupied: 12,
    daysInMonth: 31,
    method: 'actual',
  })

  return (
    <main className="mx-auto flex min-h-screen max-w-2xl flex-col justify-center gap-6 p-8">
      <header>
        <h1 className="text-2xl font-semibold tracking-tight">
          Rental Operations Platform
        </h1>
        <p className="text-muted-foreground mt-2 text-sm">
          Scaffold only. Product source of truth lives in{' '}
          <code className="font-mono">docs/prds/</code>; build order is{' '}
          <code className="font-mono">docs/prds/06-backlog.md</code>.
        </p>
      </header>

      <section aria-labelledby="invariants">
        <h2 id="invariants" className="text-sm font-semibold">
          Conventions this scaffold already enforces
        </h2>
        <ul className="text-muted-foreground mt-2 space-y-1 text-sm">
          <li>Money is integer cents. 12 of 31 days at $1,850 = {formatCents(example)}.</li>
          <li>
            Statutory numbers are clamped in core, never generated by Stripe.
            A $95 fee under a $50 cap is {formatCents(clampToStateCap(9_500, 5_000))}.
          </li>
          <li>Accessibility is asserted in CI, not deferred.</li>
        </ul>
      </section>
    </main>
  )
}
