// FCRA adverse-action notice text (LEASE-05, R-061).
//
// 15 U.S.C. § 1681m(a): anyone who takes adverse action based in whole or
// part on a consumer report must tell the consumer (1) the name, address
// and phone number of the CRA that furnished it, (2) that the CRA did not
// make the decision and cannot explain the specific reasons for it, and (3)
// the consumer's right to a free copy of the report from that CRA within 60
// days and to dispute its accuracy or completeness directly with the CRA.
// "Approve with conditions" is adverse action too - a worse offer than
// applied for, because of the report, is exactly what the statute means by
// it.
//
// A DRAFT, like every legal artifact this product generates (D-4's closing
// line, entryNoticeText's own precedent) - not reviewed by counsel, and it
// says so in its own last line.
//
// WHAT THIS IS NOT: a scoring explanation. `factors` below is the plain
// language evaluateCriteria() already wrote for each FAILS/UNKNOWN
// criterion - reproduced, never computed here. No AI or algorithmic
// applicant scoring, ever (LEASE-04's rule, restated for the one document
// that could otherwise smuggle a "risk score" back in through the notice).

export interface AdverseActionContext {
  applicantName: string
  addressLine1: string
  /// APPROVED_WITH_CONDITIONS or DECLINED - never APPROVED (no adverse
  /// action is owed for a plain approval, and this function is not called
  /// for one).
  decision: 'APPROVED_WITH_CONDITIONS' | 'DECLINED'
  /// The reporting agency's own identity, as the adapter returned it and
  /// ScreeningReport.agencyContact froze it at order time - reproduced
  /// verbatim, § 1681m(a)(1)'s requirement.
  agencyContact: string
  /// Plain-language statements for whichever criteria did not MEET,
  /// reproduced from evaluateCriteria() - "considered in this decision",
  /// never "the reason", since the statute requires naming the CRA and the
  /// right to dispute, not a itemized rationale.
  factors: readonly string[]
  /// The individualized-assessment note a staff member wrote when deciding
  /// (ScreeningReport.decisionNotes) - HUD's guidance on criminal-history
  /// screening is why this exists at all; reproduced here so the applicant
  /// sees the same reasoning the decision was actually based on.
  decisionNotes: string | null
}

/// What the compliance gate needs to know about ONE applicant's screening
/// outcome - shared by the automatic SCREENED→APPROVED advance
/// (staff-actions.ts) and the manual override gate on advanceProspectStage
/// (prospects/staff-actions.ts), so "is an adverse action still owed" is
/// answered identically in both places rather than drifting.
export interface AdverseActionStatus {
  decision: string | null
  /// Notice.servedAt for the adverse-action notice, if one exists and has
  /// been served.
  noticeSentAt: Date | null
  /// ScreeningReport.adverseActionOverriddenAt - the escape hatch.
  overriddenAt: Date | null
}

/**
 * True when this applicant's decision requires an adverse-action notice
 * (DECLINED or APPROVED_WITH_CONDITIONS) and neither the notice has been
 * sent nor the block overridden with a reason. A plain APPROVED, or an
 * undecided applicant, owes nothing.
 */
export function adverseActionOwed(status: AdverseActionStatus): boolean {
  if (status.decision !== 'DECLINED' && status.decision !== 'APPROVED_WITH_CONDITIONS') {
    return false
  }
  return status.noticeSentAt == null && status.overriddenAt == null
}

export function adverseActionNoticeText(context: AdverseActionContext): string {
  const decisionLine =
    context.decision === 'DECLINED'
      ? 'we are unable to offer you a lease for this property'
      : 'we can only offer you a lease for this property under different or additional conditions than you applied for'

  return [
    'Notice of adverse action',
    '',
    `Dear ${context.applicantName},`,
    '',
    `Based in whole or in part on information in a consumer report, ${decisionLine} at ${context.addressLine1}.`,
    '',
    'The consumer reporting agency that furnished the report was:',
    '',
    context.agencyContact,
    '',
    'That agency did not make this decision and is unable to explain the specific reasons for it.',
    '',
    'You have the right to obtain a free copy of your report from that agency if you request it within 60 days of this notice, and the right to dispute the accuracy or completeness of any information the agency furnished, directly with the agency.',
    ...(context.factors.length > 0
      ? ['', 'Factors from the report considered in this decision:', ...context.factors.map((f) => `- ${f}`)]
      : []),
    ...(context.decisionNotes ? ['', `Notes on this decision: ${context.decisionNotes}`] : []),
    '',
    '— This notice is a draft generated by the property management system and has not been reviewed by an attorney. It is not legal advice.',
  ].join('\n')
}
