import 'server-only'

import { createHash } from 'node:crypto'
import type { DocumentBlock } from '@rental/core/documents'
import { esignAdapter } from '@/lib/esign/provider.ts'
import { appendPdfs, renderBlocksPdf } from '@/lib/pdf/render.ts'
import { generateStorageKey, storage } from '@/lib/storage/index.ts'

// Building the executed PDF once every signer has completed (R-063, R-090,
// R-203).
//
// ONE COPY, THREE KINDS. This was written for a lease (esign-actions.ts),
// copied verbatim for an amendment (party-change-apply.ts), and R-203 would
// have made it three. The three differ only in the file name; every line
// that matters - fetch the draft bytes, ask the provider for its completion
// certificate, render that certificate to its own PDF, append it, hash and
// store - was identical, which is exactly the shape that rots when one copy
// is fixed and the others are not.
//
// APPENDS TO THE DRAFT'S OWN BYTES and never re-renders the body from the
// record (D-50's precedent for attaching a second PDF's pages verbatim).
// What a signer actually reviewed is what stays in the executed PDF, even if
// the underlying record is edited afterwards.

export interface ExecutedSignerFact {
  name: string
  role: 'TENANT' | 'GUARANTOR'
  order: number
  signedAt: Date | null
  signedName: string | null
  signedIp: string | null
}

export interface ArchivedExecutedDocument {
  storageKey: string
  fileName: string
  sha256: string
  sizeBytes: number
}

export async function archiveExecutedDocument(input: {
  providerId: string
  propertyId: string
  /// The whole name, extension included - the caller knows what kind of
  /// artifact this is and nothing here should be guessing at it.
  fileName: string
  draftDocument: { storageKey: string; sha256: string | null }
  signers: readonly ExecutedSignerFact[]
}): Promise<ArchivedExecutedDocument> {
  const draftBytes = await storage.get(input.draftDocument.storageKey)

  const cert = await esignAdapter.completionCertificate({
    providerId: input.providerId,
    documentSha256: input.draftDocument.sha256 ?? '',
    signers: input.signers.map((s) => ({
      name: s.signedName ?? s.name,
      role: s.role,
      order: s.order,
      signedAt: s.signedAt ?? new Date(),
      signedName: s.signedName ?? s.name,
      signedIp: s.signedIp,
    })),
  })

  const certBlocks: DocumentBlock[] = [
    { kind: 'heading', text: 'Certificate of Completion' },
    { kind: 'meta', text: `Envelope: ${input.providerId}` },
    { kind: 'meta', text: `Document hash (SHA-256): ${input.draftDocument.sha256 ?? 'unknown'}` },
    { kind: 'meta', text: `Generated: ${cert.generatedAt.toISOString()}` },
    ...cert.certificateText.split('\n').map((line) => ({ kind: 'mono' as const, text: line })),
    {
      kind: 'footer',
      text: 'Generated by a simulated e-signature provider (D-7) - not a real vendor certificate.',
    },
  ]
  const certBytes = Buffer.from(
    await renderBlocksPdf(certBlocks, { title: 'Certificate of Completion' }),
  )

  const { bytes } = await appendPdfs(draftBytes, [
    { label: 'Certificate of Completion', bytes: certBytes },
  ])
  const buffer = Buffer.from(bytes)
  const sha256 = createHash('sha256').update(buffer).digest('hex')
  const storageKey = generateStorageKey(input.propertyId, input.fileName)
  await storage.put(storageKey, buffer, 'application/pdf')
  return { storageKey, fileName: input.fileName, sha256, sizeBytes: buffer.byteLength }
}
