import 'server-only'

import { createHash } from 'node:crypto'
import type { DocumentBlock } from '@rental/core/documents'
import { prisma } from '@rental/db'
import { auditAsSystem } from '@/lib/audit/system.ts'
import { esignAdapter } from '@/lib/esign/provider.ts'
import { appendPdfs, renderBlocksPdf } from '@/lib/pdf/render.ts'
import { generateStorageKey, storage } from '@/lib/storage/index.ts'

// Every signer has signed a change-of-occupants amendment (RISK-10, R-090).
//
// WHAT THIS DOES NOT DO IS THE POINT. It does not end a lease, start one,
// touch a Stripe subscription, post a ledger entry, charge or refund a
// deposit, or open a deposit disposition. The Lease row is not written to at
// all. Everything RISK-10 asks for under "ledger continuity" and "the
// deposit stays with the unit until full turnover" is achieved by there
// being no code here that could do otherwise - see the migration's own
// header.
//
// Called from `esign-actions.ts`'s `completeEnvelope`, which is public and
// session-less, so `auditAsSystem` rather than `audit()`.

/**
 * Builds the executed PDF - the draft's own bytes with a Certificate of
 * Completion appended - and archives it.
 *
 * The amendment body pages are never re-rendered from the change record:
 * what the signers actually read is what stays in the executed PDF, even if
 * the change is described differently somewhere else later. Same rule
 * `completeEnvelope` states for a lease, and the same `appendPdfs` call.
 */
async function archiveExecutedAmendment(envelope: {
  id: string
  leaseId: string
  providerId: string
  propertyId: string
  draftDocument: { storageKey: string; sha256: string | null }
  signers: readonly {
    name: string
    role: 'TENANT' | 'GUARANTOR'
    order: number
    signedAt: Date | null
    signedName: string | null
    signedIp: string | null
  }[]
}): Promise<{ storageKey: string; fileName: string; sha256: string; sizeBytes: number }> {
  const draftBytes = await storage.get(envelope.draftDocument.storageKey)

  const cert = await esignAdapter.completionCertificate({
    providerId: envelope.providerId,
    documentSha256: envelope.draftDocument.sha256 ?? '',
    signers: envelope.signers.map((s) => ({
      name: s.signedName ?? s.name,
      role: s.role,
      order: s.order,
      signedAt: s.signedAt ?? new Date(),
      signedName: s.signedName ?? s.name,
      signedIp: s.signedIp,
    })),
  })

  const certBlocks: DocumentBlock[] = [
    { kind: 'heading', text: 'Certificate of Completion' },
    { kind: 'meta', text: `Envelope: ${envelope.providerId}` },
    { kind: 'meta', text: `Document hash (SHA-256): ${envelope.draftDocument.sha256 ?? 'unknown'}` },
    { kind: 'meta', text: `Generated: ${cert.generatedAt.toISOString()}` },
    ...cert.certificateText.split('\n').map((line) => ({ kind: 'mono' as const, text: line })),
    {
      kind: 'footer',
      text: 'Generated by a simulated e-signature provider (D-7) - not a real vendor certificate.',
    },
  ]
  const certBytes = Buffer.from(
    await renderBlocksPdf(certBlocks, { title: 'Certificate of Completion' }),
  )
  const { bytes } = await appendPdfs(draftBytes, [
    { label: 'Certificate of Completion', bytes: certBytes },
  ])
  const buffer = Buffer.from(bytes)
  const sha256 = createHash('sha256').update(buffer).digest('hex')
  const fileName = `lease-amendment-executed-${envelope.id}.pdf`
  const storageKey = generateStorageKey(envelope.propertyId, fileName)
  await storage.put(storageKey, buffer, 'application/pdf')
  return { storageKey, fileName, sha256, sizeBytes: buffer.byteLength }
}

export async function completePartyChangeEnvelope(envelopeId: string): Promise<void> {
  const envelope = await prisma.leaseEnvelope.findUniqueOrThrow({
    where: { id: envelopeId },
    include: {
      lease: { select: { id: true, propertyId: true, status: true } },
      draftDocument: true,
      signers: { orderBy: { order: 'asc' } },
      partyChange: { include: { parties: true } },
    },
  })
  if (envelope.status === 'COMPLETED' || !envelope.draftDocument || !envelope.providerId) return

  const change = envelope.partyChange
  if (!change || change.status !== 'PENDING_SIGNATURE') {
    console.error(
      `[party-change] envelope ${envelopeId} completed with no pending change attached - nothing applied`,
    )
    return
  }

  const archived = await archiveExecutedAmendment({
    id: envelope.id,
    leaseId: envelope.leaseId,
    providerId: envelope.providerId,
    propertyId: envelope.lease.propertyId,
    draftDocument: envelope.draftDocument,
    signers: envelope.signers,
  })

  const outgoingTenantIds = change.parties
    .filter((p) => p.direction === 'OUTGOING')
    .map((p) => p.tenantId)
  const incoming = change.parties.filter((p) => p.direction === 'INCOMING')

  await prisma.$transaction(async (tx) => {
    const document = await tx.document.create({
      data: {
        propertyId: envelope.lease.propertyId,
        leaseId: envelope.leaseId,
        type: 'LEASE_AMENDMENT',
        fileName: archived.fileName,
        contentType: 'application/pdf',
        sizeBytes: archived.sizeBytes,
        storageKey: archived.storageKey,
        sha256: archived.sha256,
      },
    })
    await tx.leaseEnvelope.update({
      where: { id: envelope.id },
      data: { status: 'COMPLETED', completedAt: new Date(), executedDocumentId: document.id },
    })

    const removed = await tx.leaseTenant.findMany({
      where: { leaseId: envelope.leaseId, tenantId: { in: outgoingTenantIds } },
      select: { id: true, tenantId: true, isPrimary: true },
    })
    if (removed.length > 0) {
      await tx.leaseTenant.deleteMany({ where: { id: { in: removed.map((r) => r.id) } } })
      // The departing occupant's every issued session dies with their
      // tenancy. Without this they keep a live portal session to a home they
      // no longer rent until the token happens to expire - the portal
      // authorizes from the session, not from a fresh LeaseTenant read.
      await tx.tenant.updateMany({
        where: { id: { in: removed.map((r) => r.tenantId) } },
        data: { sessionsValidFrom: new Date() },
      })
    }

    for (const party of incoming) {
      await tx.leaseTenant.create({
        data: { leaseId: envelope.leaseId, tenantId: party.tenantId, isPrimary: false },
      })
    }

    // Somebody has to be the primary: every single-recipient message in this
    // product addresses them (see LeaseTenant.isPrimary's own comment). If
    // the primary just left, the longest-standing remaining occupant takes
    // it - and the audit entry below says so, because "who is the primary
    // now" is otherwise a silent consequence of a form somebody filled in.
    let promotedTenantId: string | null = null
    if (removed.some((r) => r.isPrimary)) {
      const successor = await tx.leaseTenant.findFirst({
        where: { leaseId: envelope.leaseId },
        orderBy: { createdAt: 'asc' },
        select: { id: true, tenantId: true },
      })
      if (successor) {
        await tx.leaseTenant.update({ where: { id: successor.id }, data: { isPrimary: true } })
        promotedTenantId = successor.tenantId
      }
    }

    await tx.leasePartyChange.update({
      where: { id: change.id },
      data: { status: 'COMPLETED', appliedAt: new Date() },
    })

    await auditAsSystem(
      'esign.completion',
      {
        action: 'envelope.completed',
        entityType: 'LeaseEnvelope',
        entityId: envelope.id,
        propertyId: envelope.lease.propertyId,
        after: {
          kind: 'AMENDMENT',
          changeId: change.id,
          executedDocumentId: document.id,
          sha256: archived.sha256,
          signerCount: envelope.signers.length,
        },
      },
      tx,
    )
    await auditAsSystem(
      'esign.completion',
      {
        action: 'lease.party_changed',
        entityType: 'Lease',
        entityId: envelope.leaseId,
        propertyId: envelope.lease.propertyId,
        reason: change.reason,
        before: { primaryTenantId: removed.find((r) => r.isPrimary)?.tenantId ?? null },
        after: {
          changeId: change.id,
          effectiveOn: change.effectiveOn.toISOString().slice(0, 10),
          removedTenantIds: removed.map((r) => r.tenantId),
          addedTenantIds: incoming.map((p) => p.tenantId),
          screenedApplicantIds: incoming.map((p) => p.applicantId),
          promotedPrimaryTenantId: promotedTenantId,
          executedDocumentId: document.id,
        },
      },
      tx,
    )
  })
}
