import 'server-only'

import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import type { StorageAdapter } from './adapter.ts'

/**
 * Disk-backed storage (D-14): dev/test today, real infrastructure behind the
 * same interface once this deploys somewhere the filesystem is not durable
 * across instances (Vercel Blob is the natural swap on this stack).
 *
 * `contentType` is accepted, not used - a local file has no content-type
 * metadata of its own the way an S3 object does; it is re-read from the
 * Document row when serving the file back out (apps/web/app/api/documents).
 */
export class LocalDiskStorageAdapter implements StorageAdapter {
  private readonly root: string

  constructor(root: string) {
    this.root = resolve(root)
  }

  private pathFor(key: string): string {
    const full = resolve(this.root, key)
    // storageKey is always generated by generateStorageKey() (index.ts), never
    // taken from user input - this is the cheap backstop if that ever changes,
    // not the primary defense.
    if (!full.startsWith(this.root)) {
      throw new Error(`Refusing to access a path outside the storage root: ${key}`)
    }
    return full
  }

  async put(key: string, data: Buffer): Promise<void> {
    const path = this.pathFor(key)
    await mkdir(dirname(path), { recursive: true })
    await writeFile(path, data)
  }

  async get(key: string): Promise<Buffer> {
    return readFile(this.pathFor(key))
  }

  async delete(key: string): Promise<void> {
    await rm(this.pathFor(key), { force: true })
  }
}
